package com.pivotree.appzone.enums;

public enum FulfillmentStatus {
    CREATED, ASSIGNED, SYSTEMREJECTED, REFUNDED, ACKNOWLEDGED, FULFILLED, PARTIALLYFULFILLED,
    REJECTED, PACKED, SHIPPED, DELIVERED, READYTOCOLLECT, COLLECTED
}
